env                              = "staging"
project_id                       = "gateway-417423"
region                           = "europe-west2"
project_number                   = "270538298374"
dataform_staging_service_account = "dataform-staging"
dataform_prod_service_account    = "dataform-prod@gateway-417423.iam.gserviceaccount.com"
dataform_github_token            = "dataform_github_token"