project_id                    = "{project-id}"
region                        = "{project-region}"
project_number                = "{project-number}"
dataform_prod_service_account = "dataform-prod"
staging_project_number        = "{staging-project-number}"